apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::173272682523:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J11QUCA0JLG1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::173272682523:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-01T12:41:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1647"
  uid: 7d0d798f-2116-4737-9aa8-bd9ae4e8db5b
